### ISSUE TITLE
需要的几个变量oulu_token,notion_token, database_id都是咋获取的呀, 有b站视频介绍不?谢啦

### ISSUE THREAD

**Issue by AfreyAwsome** [cxq-haha/oulu_to_notion#1]
需要的几个变量oulu_token,notion_token, database_id都是咋获取的呀, 有b站视频介绍不?谢啦

**Comment by cxq-haha** [comment]
@AfreyAwsome 可以参考这个文档哈 https://my.eudic.net/OpenAPI/Doc_Index

**Comment by AfreyAwsome** [comment]
> @AfreyAwsome 可以参考这个文档哈 https://my.eudic.net/OpenAPI/Doc_Index

get, 3q
